import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";

import { NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing"; // щоб дістати масив локалей

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Makeup by Nikush",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  /* -------------------------------------------------
     1. Перевіряємо, чи підтримується запитана локаль.
        Інакше — падаємо на defaultLocale (uk).
  --------------------------------------------------*/
  const supported = routing.locales as readonly string[];
  const resolvedLocale = supported.includes(locale)
    ? locale
    : routing.defaultLocale;

  /* -------------------------------------------------
     2. Підтягуємо відповідний словник.
        Тут import завжди вдається, бо resolvedLocale валідний.
  --------------------------------------------------*/
  const messages = (await import(`@/messages/${resolvedLocale}.json`)).default;

  return (
    <html
      lang={resolvedLocale}
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body suppressHydrationWarning className="antialiased">
        <NextIntlClientProvider locale={resolvedLocale} messages={messages}>
          <ClientBody>{children}</ClientBody>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
